<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Permisos del Sistema Tramite Judicial',
                'slug' => 'sistema',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => NULL,
                'permiso' => 1,
                'nivel' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Permisos de los Modulos Usuarios, Roles y Permisos',
                'slug' => 'users.roles.permisos',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 1,
                'permiso' => 0,
                'nivel' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Permisos del Modulo Usuarios del Sistema',
                'slug' => 'users',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 2,
                'permiso' => 0,
                'nivel' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Navegar usuarios',
                'slug' => 'users.index',
                'description' => 'Lista y navega todos los usuarios del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 3,
                'permiso' => 0,
                'nivel' => 0,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Ver detalle de usuario',
                'slug' => 'users.show',
                'description' => 'Ver en detalle cada usuario del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 3,
                'permiso' => 0,
                'nivel' => 0,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Creación de usuario',
                'slug' => 'users.create',
                'description' => 'Podrá crear nuevos usuarios en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 3,
                'permiso' => 0,
                'nivel' => 0,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Edición de usuarios',
                'slug' => 'users.edit',
                'description' => 'Podría editar cualquier dato de un usuario del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 3,
                'permiso' => 0,
                'nivel' => 0,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Eliminar usuario',
                'slug' => 'users.destroy',
                'description' => 'Podría eliminar cualquier usuario del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 3,
                'permiso' => 0,
                'nivel' => 0,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Permisos del Modulo Roles del Sistema',
                'slug' => 'roles',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 2,
                'permiso' => 0,
                'nivel' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Navegar roles',
                'slug' => 'roles.index',
                'description' => 'Lista y navega todos los roles del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 9,
                'permiso' => 0,
                'nivel' => 0,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Ver detalle de un rol',
                'slug' => 'roles.show',
                'description' => 'Ver en detalle cada rol del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 9,
                'permiso' => 0,
                'nivel' => 0,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Creación de roles',
                'slug' => 'roles.create',
                'description' => 'Podría crear nuevos roles en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 9,
                'permiso' => 0,
                'nivel' => 0,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Edición de roles',
                'slug' => 'roles.edit',
                'description' => 'Podría editar cualquier dato de un rol del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 9,
                'permiso' => 0,
                'nivel' => 0,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Eliminar roles',
                'slug' => 'roles.destroy',
                'description' => 'Podría eliminar cualquier rol del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 9,
                'permiso' => 0,
                'nivel' => 0,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Permisos del Modulo Permisos del Sistema',
                'slug' => 'permisos',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 2,
                'permiso' => 0,
                'nivel' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Navegar permisos',
                'slug' => 'permisos.index',
                'description' => 'Lista y navega todos los permisos del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 15,
                'permiso' => 0,
                'nivel' => 0,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Ver detalle de un permiso',
                'slug' => 'permisos.show',
                'description' => 'Ver en detalle cada permiso del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 15,
                'permiso' => 0,
                'nivel' => 0,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Creación de permisos',
                'slug' => 'permisos.create',
                'description' => 'Podría crear nuevos permisos en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 15,
                'permiso' => 0,
                'nivel' => 0,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Edición de permisos',
                'slug' => 'permisos.edit',
                'description' => 'Podría editar cualquier dato de un permiso del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 15,
                'permiso' => 0,
                'nivel' => 0,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Eliminar permisos',
                'slug' => 'permisos.destroy',
                'description' => 'Podría eliminar cualquier permiso del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 15,
                'permiso' => 0,
                'nivel' => 0,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Permisos de los Modulos Tablas Maestras',
                'slug' => 'tabla.maestras',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 1,
                'permiso' => 0,
                'nivel' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Permisos del Modulo Centros de Salud',
                'slug' => 'centrosalud',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Navegar centros de salud',
                'slug' => 'centrosalud.index',
                'description' => 'Lista y navega todos los centros de salud del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 22,
                'permiso' => 0,
                'nivel' => 0,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Ver detalle de un centro de salud',
                'slug' => 'centrosalud.show',
                'description' => 'Ve en detalle cada centro de salud del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 22,
                'permiso' => 0,
                'nivel' => 0,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Creación de centros de salud',
                'slug' => 'centrosalud.create',
                'description' => 'Podría crear nuevos centros de salud en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 22,
                'permiso' => 0,
                'nivel' => 0,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Edición de centros de salud',
                'slug' => 'centrosalud.edit',
                'description' => 'Podría editar cualquier dato de un centro de salud del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 22,
                'permiso' => 0,
                'nivel' => 0,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Eliminar centros de salud',
                'slug' => 'centrosalud.destroy',
                'description' => 'Podría eliminar cualquier centro de salud del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 22,
                'permiso' => 0,
                'nivel' => 0,
            ),
            27 => 
            array (
                'id' => 28,
            'name' => 'Permisos del Modulo Institucionesc (Comisarias, CEM, Minesterio Público, etc.)',
                'slug' => 'comisaria',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Navegar comisarias',
                'slug' => 'comisaria.index',
                'description' => 'Lista y navega todos las comisarias del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 28,
                'permiso' => 0,
                'nivel' => 0,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Ver detalle de una comisaria',
                'slug' => 'comisaria.show',
                'description' => 'Ve en detalle cada comisaria del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 28,
                'permiso' => 0,
                'nivel' => 0,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Creación de comisarias',
                'slug' => 'comisaria.create',
                'description' => 'Podría crear nuevas comisarias en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 28,
                'permiso' => 0,
                'nivel' => 0,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'Edición de comisarias',
                'slug' => 'comisaria.edit',
                'description' => 'Podría editar cualquier dato de una comisaria del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 28,
                'permiso' => 0,
                'nivel' => 0,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Eliminar comisarias',
                'slug' => 'comisaria.destroy',
                'description' => 'Podría eliminar cualquier comisaria del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 28,
                'permiso' => 0,
                'nivel' => 0,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Permisos del Modulo Instancias',
                'slug' => 'instancia',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Navegar instancias',
                'slug' => 'instancia.index',
                'description' => 'Lista y navega todos las instancias del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 34,
                'permiso' => 0,
                'nivel' => 0,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Ver detalle de una instancia',
                'slug' => 'instancia.show',
                'description' => 'Ve en detalle cada instancia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 34,
                'permiso' => 0,
                'nivel' => 0,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Creación de instancias',
                'slug' => 'instancia.create',
                'description' => 'Podría crear nuevas instancias en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 34,
                'permiso' => 0,
                'nivel' => 0,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Edición de instancias',
                'slug' => 'instancia.edit',
                'description' => 'Podría editar cualquier dato de una instancia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 34,
                'permiso' => 0,
                'nivel' => 0,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Eliminar instancias',
                'slug' => 'instancia.destroy',
                'description' => 'Podría eliminar cualquier instancia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 34,
                'permiso' => 0,
                'nivel' => 0,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Permisos del Modulo Motivos',
                'slug' => 'motivo',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Navegar motivos',
                'slug' => 'motivo.index',
                'description' => 'Lista y navega todos los motivos del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 40,
                'permiso' => 0,
                'nivel' => 0,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Ver detalle de un motivo',
                'slug' => 'motivo.show',
                'description' => 'Ve en detalle cada motivo del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 40,
                'permiso' => 0,
                'nivel' => 0,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Creación de motivos',
                'slug' => 'motivo.create',
                'description' => 'Podría crear nuevos motivos en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 40,
                'permiso' => 0,
                'nivel' => 0,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Edición de motivos',
                'slug' => 'motivo.edit',
                'description' => 'Podría editar cualquier dato de un motivo del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 40,
                'permiso' => 0,
                'nivel' => 0,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'Eliminar motivos',
                'slug' => 'motivo.destroy',
                'description' => 'Podría eliminar cualquier motivo del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 40,
                'permiso' => 0,
                'nivel' => 0,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Permisos del Modulo Documentos',
                'slug' => 'documento',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'Navegar documentos',
                'slug' => 'documento.index',
                'description' => 'Lista y navega todos los documentos del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 46,
                'permiso' => 0,
                'nivel' => 0,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Ver detalle de un documento',
                'slug' => 'documento.show',
                'description' => 'Ve en detalle cada documento del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 46,
                'permiso' => 0,
                'nivel' => 0,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Creación de documentos',
                'slug' => 'documento.create',
                'description' => 'Podría crear nuevos documentos en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 46,
                'permiso' => 0,
                'nivel' => 0,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Edición de documentos',
                'slug' => 'documento.edit',
                'description' => 'Podría editar cualquier dato de un documento del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 46,
                'permiso' => 0,
                'nivel' => 0,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Eliminar documentos',
                'slug' => 'documento.destroy',
                'description' => 'Podría eliminar cualquier documento del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 46,
                'permiso' => 0,
                'nivel' => 0,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Permisos del Modulo Tipos',
                'slug' => 'tipo',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'Navegar tipos',
                'slug' => 'tipo.index',
                'description' => 'Lista y navega todos los tipos del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 52,
                'permiso' => 0,
                'nivel' => 0,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Ver detalle de un tipo',
                'slug' => 'tipo.show',
                'description' => 'Ve en detalle cada tipo del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 52,
                'permiso' => 0,
                'nivel' => 0,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Creación de tipos',
                'slug' => 'tipo.create',
                'description' => 'Podría crear nuevos tipos en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 52,
                'permiso' => 0,
                'nivel' => 0,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Edición de tipos',
                'slug' => 'tipo.edit',
                'description' => 'Podría editar cualquier dato de un tipo del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 52,
                'permiso' => 0,
                'nivel' => 0,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Eliminar tipos',
                'slug' => 'tipo.destroy',
                'description' => 'Podría eliminar cualquier tipo del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 52,
                'permiso' => 0,
                'nivel' => 0,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Permisos del Modulo Parentescos',
                'slug' => 'parentesco',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Navegar parentescos',
                'slug' => 'parentesco.index',
                'description' => 'Lista y navega todos los parentescos del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 58,
                'permiso' => 0,
                'nivel' => 0,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Ver detalle de un parentesco',
                'slug' => 'parentesco.show',
                'description' => 'Ve en detalle cada parentesco del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 58,
                'permiso' => 0,
                'nivel' => 0,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Creación de parentescos',
                'slug' => 'parentesco.create',
                'description' => 'Podría crear nuevos parentescos en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 58,
                'permiso' => 0,
                'nivel' => 0,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Edición de parentescos',
                'slug' => 'parentesco.edit',
                'description' => 'Podría editar cualquier dato de un parentesco del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 58,
                'permiso' => 0,
                'nivel' => 0,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Eliminar parentescos',
                'slug' => 'parentesco.destroy',
                'description' => 'Podría eliminar cualquier parentesco del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 58,
                'permiso' => 0,
                'nivel' => 0,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'Permisos del Modulo Tipos de Denuncia',
                'slug' => 'tdenucia',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Navegar tipos de denuncia',
                'slug' => 'tdenuncia.index',
                'description' => 'Lista y navega todos los tipos de denuncia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 64,
                'permiso' => 0,
                'nivel' => 0,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Ver detalle de un tipo de denuncia',
                'slug' => 'tdenuncia.show',
                'description' => 'Ve en detalle cada tipo de denuncia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 64,
                'permiso' => 0,
                'nivel' => 0,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'Creación de tipos de denuncia',
                'slug' => 'tdenuncia.create',
                'description' => 'Podría crear nuevos tipos de denuncia en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 64,
                'permiso' => 0,
                'nivel' => 0,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Edición de tipos de denuncia',
                'slug' => 'tdenuncia.edit',
                'description' => 'Podría editar cualquier dato de un tipo de denuncia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 64,
                'permiso' => 0,
                'nivel' => 0,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Eliminar tipos de denuncia',
                'slug' => 'tdenuncia.destroy',
                'description' => 'Podría eliminar cualquier tipo de denuncia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 64,
                'permiso' => 0,
                'nivel' => 0,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Permisos de los Modulos Ley N° 30364',
                'slug' => '30364',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 1,
                'permiso' => 0,
                'nivel' => 1,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Permisos de los Modulo Denuncia, Victimas y Agresores',
                'slug' => 'denuncia.victima.agresor',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 70,
                'permiso' => 0,
                'nivel' => 1,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Permisos del Modulo Registro Denuncia',
                'slug' => 'denuncia',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 71,
                'permiso' => 0,
                'nivel' => 1,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Navegar denuncias',
                'slug' => 'denuncia.index',
                'description' => 'Lista y navega todas las denuncias del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 0,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Ver detalle de un denuncia',
                'slug' => 'denuncia.show',
                'description' => 'Ve en detalle cada denuncia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 0,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Obtener informacion de las denuncias',
                'slug' => 'denuncia.getGData',
                'description' => 'Obtener informacion de las denuncias',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 0,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'Generar reportes de denuncia',
                'slug' => 'denuncia.report',
                'description' => 'Generar reportes de denuncia',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 70,
                'permiso' => 0,
                'nivel' => 0,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'Importar denuncias',
                'slug' => 'denuncia.import',
                'description' => 'Importar denuncias',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 70,
                'permiso' => 0,
                'nivel' => 0,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'Importar CSV denuncias',
                'slug' => 'denuncia.importcsv',
                'description' => 'Importar CSV denuncias',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 70,
                'permiso' => 0,
                'nivel' => 0,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'Generar reportes estadisticos de denuncia',
                'slug' => 'denuncia.estadistica',
                'description' => 'Generar reportes estadisticos de denuncia',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 70,
                'permiso' => 0,
                'nivel' => 0,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Creación de denuncias',
                'slug' => 'denuncia.create',
                'description' => 'Podría crear nuevas denuncias en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 0,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Edición de denuncias',
                'slug' => 'denuncia.edit',
                'description' => 'Podría editar cualquier dato de una denuncia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 0,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Subir documento de archivo policial',
                'slug' => 'denuncia.file',
                'description' => 'Podría subir documento de archivo policial de una denuncia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 0,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Eliminar denuncias',
                'slug' => 'denuncia.destroy',
                'description' => 'Podría eliminar cualquier denuncia del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 0,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Permisos del Modulo Victimas',
                'slug' => 'victima',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 71,
                'permiso' => 0,
                'nivel' => 1,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Navegar victimas',
                'slug' => 'victima.index',
                'description' => 'Lista y navega todas las victimas del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 84,
                'permiso' => 0,
                'nivel' => 0,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Ver detalle de un victima',
                'slug' => 'victima.show',
                'description' => 'Ve en detalle cada victima del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 84,
                'permiso' => 0,
                'nivel' => 0,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Creación de victimas',
                'slug' => 'victima.create',
                'description' => 'Podría crear nuevas victimas en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 84,
                'permiso' => 0,
                'nivel' => 0,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Edición de victimas',
                'slug' => 'victima.edit',
                'description' => 'Podría editar cualquier dato de una victima del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 84,
                'permiso' => 0,
                'nivel' => 0,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Eliminar victimas',
                'slug' => 'victima.destroy',
                'description' => 'Podría eliminar cualquier victima del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 84,
                'permiso' => 0,
                'nivel' => 0,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'Permisos del Modulo Agresores',
                'slug' => 'agresor',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 71,
                'permiso' => 0,
                'nivel' => 1,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'Navegar agresores',
                'slug' => 'agresor.index',
                'description' => 'Lista y navega todos los agresores del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 90,
                'permiso' => 0,
                'nivel' => 0,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'Ver detalle de un agresor',
                'slug' => 'agresor.show',
                'description' => 'Ve en detalle cada agresor del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 90,
                'permiso' => 0,
                'nivel' => 0,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'Creación de agresores',
                'slug' => 'agresor.create',
                'description' => 'Podría crear nuevos agresores en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 90,
                'permiso' => 0,
                'nivel' => 0,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'Edición de agresores',
                'slug' => 'agresor.edit',
                'description' => 'Podría editar cualquier dato de un agresor del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 90,
                'permiso' => 0,
                'nivel' => 0,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'Eliminar agresores',
                'slug' => 'agresor.destroy',
                'description' => 'Podría eliminar cualquier agresor del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 90,
                'permiso' => 0,
                'nivel' => 0,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'Permisos del Modulo Notificaciones',
                'slug' => 'notificacion',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 70,
                'permiso' => 0,
                'nivel' => 1,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'Navegar notificaciones',
                'slug' => 'notification.index',
                'description' => 'Lista y navega todos los notificaciones del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 96,
                'permiso' => 0,
                'nivel' => 0,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'Ver detalle de un notificacion',
                'slug' => 'notification.show',
                'description' => 'Ve en detalle cada notificacion del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 96,
                'permiso' => 0,
                'nivel' => 0,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'Creación de notificaciones',
                'slug' => 'notification.create',
                'description' => 'Podría crear nuevos notificaciones en el sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 96,
                'permiso' => 0,
                'nivel' => 0,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'Edición de notificaciones',
                'slug' => 'notification.edit',
                'description' => 'Podría editar cualquier dato de un notificacion del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 96,
                'permiso' => 0,
                'nivel' => 0,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'Eliminar notificaciones',
                'slug' => 'notification.destroy',
                'description' => 'Podría eliminar cualquier notificacion del sistema',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 96,
                'permiso' => 0,
                'nivel' => 0,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'Acceso a las Pestañas de las Denuncias',
                'slug' => 'acceso',
                'description' => NULL,
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 1,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'Victima',
                'slug' => 'acceso.victima',
            'description' => 'Agrega una victima(s) a la denuncia',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'Agresores',
                'slug' => 'acceso.agresores',
            'description' => 'Agrega un agresor(es) a la denuncia',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'CEM',
                'slug' => 'acceso.cem',
                'description' => 'Centro de emergencia mujer',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'Denuncia',
                'slug' => 'acceso.denuncia',
                'description' => 'Agrega información a la denuncia',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'Modulo Familia',
                'slug' => 'acceso.familia',
                'description' => 'Agrega información a la denuncia del modulo familia',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'Remisión',
                'slug' => 'acceso.remision',
                'description' => 'Remisión de la denuncia a fase II',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'Fase II',
                'slug' => 'acceso.faseii',
                'description' => 'Agrega información a la denuncia en la fase II',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'Fase III',
                'slug' => 'acceso.faseiii',
                'description' => 'Agrega información a la denuncia en la fase III',
                'created_at' => '2019-02-06 19:13:00',
                'updated_at' => '2019-02-06 19:13:00',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'Escanear registro policial',
                'slug' => 'acceso.scaner',
                'description' => 'Permite subir el documento escaneado del registro policial',
                'created_at' => '2019-03-23 18:07:03',
                'updated_at' => '2019-03-23 18:07:03',
                'depende_de' => 102,
                'permiso' => 0,
                'nivel' => 0,
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'Permiso del Modulo Tipo Denuncia Penal',
                'slug' => 'tbldpenal',
                'description' => NULL,
                'created_at' => '2019-03-25 09:15:04',
                'updated_at' => '2019-03-25 09:15:04',
                'depende_de' => 21,
                'permiso' => 0,
                'nivel' => 1,
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'Navegar tipo denuncia penal',
                'slug' => 'tbldpenal.index',
                'description' => 'Lista y navega todos los tipos de denuncias penales del sistema',
                'created_at' => '2019-03-25 09:16:43',
                'updated_at' => '2019-03-25 09:16:43',
                'depende_de' => 112,
                'permiso' => 0,
                'nivel' => 0,
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'Ver detalle tipo denuncia penal',
                'slug' => 'tbldpenal.show',
                'description' => 'Ve en detalle cada tipo denuncia penal del sistema',
                'created_at' => '2019-03-25 09:23:01',
                'updated_at' => '2019-03-25 09:23:01',
                'depende_de' => 112,
                'permiso' => 0,
                'nivel' => 0,
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'Creación de tipo denuncia penal',
                'slug' => 'tbldpenal.create',
                'description' => 'Podría crear nuevos tipos denuncias penales en el sistema',
                'created_at' => '2019-03-25 09:24:50',
                'updated_at' => '2019-03-25 09:24:50',
                'depende_de' => 112,
                'permiso' => 0,
                'nivel' => 0,
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'Edición de tipos denuncias penales',
                'slug' => 'tbldpenal.edit',
                'description' => 'Podría editar cualquier dato de un tipo denuncia penal del sistema',
                'created_at' => '2019-03-25 09:26:51',
                'updated_at' => '2019-03-25 09:26:51',
                'depende_de' => 112,
                'permiso' => 0,
                'nivel' => 0,
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'Eliminar tipo denuncia penal',
                'slug' => 'tbldpenal.destroy',
                'description' => 'Podría eliminar cualquier tipo denuncia penal del sistema',
                'created_at' => '2019-03-25 09:28:25',
                'updated_at' => '2019-03-25 09:28:25',
                'depende_de' => 112,
                'permiso' => 0,
                'nivel' => 0,
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'Informar ejecución',
                'slug' => 'denuncia.ejecucion',
                'description' => 'Informar ejecución',
                'created_at' => '2019-04-21 20:02:26',
                'updated_at' => '2019-04-21 20:02:26',
                'depende_de' => 72,
                'permiso' => 0,
                'nivel' => 0,
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'Permisos del modulo Doc. Digitalizados',
                'slug' => 'ddocumento',
                'description' => NULL,
                'created_at' => '2019-04-22 07:09:13',
                'updated_at' => '2019-04-22 07:09:13',
                'depende_de' => 70,
                'permiso' => 0,
                'nivel' => 1,
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'Navegar documentos digitalizados',
                'slug' => 'ddocumento.index',
                'description' => 'Navegar documentos digitalizados',
                'created_at' => '2019-04-22 07:09:59',
                'updated_at' => '2019-04-22 07:09:59',
                'depende_de' => 119,
                'permiso' => 0,
                'nivel' => 0,
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'Ver detalle de un documento digitalizado',
                'slug' => 'ddocumento.show',
                'description' => 'Ver detalle de un documento digitalizado',
                'created_at' => '2019-04-22 07:11:20',
                'updated_at' => '2019-04-22 07:11:20',
                'depende_de' => 119,
                'permiso' => 0,
                'nivel' => 0,
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'Crear documento digitalizado',
                'slug' => 'ddocumento.create',
                'description' => 'Crear documento digitalizado',
                'created_at' => '2019-04-22 07:14:07',
                'updated_at' => '2019-04-22 07:14:07',
                'depende_de' => 119,
                'permiso' => 0,
                'nivel' => 0,
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'Editar documento digitalizado',
                'slug' => 'ddocumento.edit',
                'description' => 'Editar documento digitalizado',
                'created_at' => '2019-04-22 07:14:47',
                'updated_at' => '2019-04-22 07:14:47',
                'depende_de' => 119,
                'permiso' => 0,
                'nivel' => 0,
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'Eliminar documento digitalizado',
                'slug' => 'ddocumento.destroy',
                'description' => 'Eliminar documento digitalizado',
                'created_at' => '2019-04-22 07:15:28',
                'updated_at' => '2019-04-22 07:15:28',
                'depende_de' => 119,
                'permiso' => 0,
                'nivel' => 0,
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'Descargar documento digitalizado',
                'slug' => 'ddocumento.download',
                'description' => 'Descargar documento digitalizado',
                'created_at' => '2019-04-22 07:17:06',
                'updated_at' => '2019-04-22 07:17:06',
                'depende_de' => 119,
                'permiso' => 0,
                'nivel' => 0,
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'Verificar documento digitalizado',
                'slug' => 'ddocumento.verificar',
                'description' => 'Verificar documento digitalizado',
                'created_at' => '2019-04-22 07:18:27',
                'updated_at' => '2019-04-22 07:18:27',
                'depende_de' => 119,
                'permiso' => 0,
                'nivel' => 0,
            ),
        ));
        
        
    }
}