<?php

use Illuminate\Database\Seeder;

class TblcomisariaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('tblcomisaria')->delete();

        \DB::table('tblcomisaria')->insert(array (
            0 =>
            array (
                'id' => 1,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'MODULO  GREGORIO ALBARRACIN',
                'sigla' => 'MDO-GAL',
                'latitud' => '-18.04321999052861',
                'longitud' => '-70.25113437612765',
                'created_at' => NULL,
                'updated_at' => '2019-03-08 13:36:34',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'yellow',
            ),
            1 =>
            array (
                'id' => 2,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Poder Judicial',
                'sigla' => 'OTROS',
                'latitud' => '-18.010601',
                'longitud' => '-70.253930',
                'created_at' => NULL,
                'updated_at' => '2019-02-25 09:13:46',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'purple',
            ),
            2 =>
            array (
                'id' => 3,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Gregorio Albarracín',
                'sigla' => 'C-GAL',
                'latitud' => '-18.041866',
                'longitud' => '-70.251253',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 12:38:39',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            3 =>
            array (
                'id' => 4,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Ciudad Nueva',
                'sigla' => 'C-CN',
                'latitud' => '-17.984271',
                'longitud' => '-70.235475',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 12:38:52',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            4 =>
            array (
                'id' => 5,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Alto de la Alianza',
                'sigla' => 'C-AL',
                'latitud' => '-17.987922',
                'longitud' => '-70.241195',
                'created_at' => NULL,
                'updated_at' => '2019-02-22 22:18:39',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            5 =>
            array (
                'id' => 6,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Central',
                'sigla' => 'C-C',
                'latitud' => '-18.014765',
                'longitud' => '-70.251784',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 12:39:14',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            6 =>
            array (
                'id' => 7,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Natividad',
                'sigla' => 'C-N',
                'latitud' => '-18.011738',
                'longitud' => '-70.233184',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 12:39:24',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            7 =>
            array (
                'id' => 8,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Leguía',
                'sigla' => 'C-L',
                'latitud' => '-18.034372',
                'longitud' => '-70.276660',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:31:39',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            8 =>
            array (
                'id' => 9,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Pocollay',
                'sigla' => 'C-P',
                'latitud' => '-17.995188',
                'longitud' => '-70.220063',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:31:49',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            9 =>
            array (
                'id' => 10,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Vigil',
                'sigla' => 'C-V',
                'latitud' => '-17.997524',
                'longitud' => '-70.245652',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:32:00',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            10 =>
            array (
                'id' => 11,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Pachia',
                'sigla' => 'C-PA',
                'latitud' => '-17.895296',
                'longitud' => '-70.152744',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:32:11',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            11 =>
            array (
                'id' => 12,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Boca del Rio',
                'sigla' => 'C-BR',
                'latitud' => '-18.156744',
                'longitud' => '-70.679107',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:32:22',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            12 =>
            array (
                'id' => 13,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Calana',
                'sigla' => 'C-CA',
                'latitud' => '-17.940560',
                'longitud' => '-70.186899',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:32:33',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            13 =>
            array (
                'id' => 14,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Sama las Yaras',
                'sigla' => 'C-SY',
                'latitud' => '-17.862860',
                'longitud' => '-70.560096',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:32:54',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            14 =>
            array (
                'id' => 15,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Sama Inclan',
                'sigla' => 'C-SI',
                'latitud' => '-17.794749',
                'longitud' => '-70.494779',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:33:08',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            15 =>
            array (
                'id' => 16,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Ite',
                'sigla' => 'C-ITE',
                'latitud' => '-17.861950',
                'longitud' => '-70.965062',
                'created_at' => NULL,
                'updated_at' => '2019-02-21 14:33:25',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            16 =>
            array (
                'id' => 17,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ANCON',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            17 =>
            array (
                'id' => 18,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP VITARTE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            18 =>
            array (
                'id' => 19,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ROSA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            19 =>
            array (
                'id' => 20,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP HUAYCAN',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            20 =>
            array (
                'id' => 21,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SALAMANCA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            21 =>
            array (
                'id' => 22,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP BARRANCO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            22 =>
            array (
                'id' => 23,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP BREÑA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            23 =>
            array (
                'id' => 24,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CARABAYLLO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            24 =>
            array (
                'id' => 25,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL PROGRESO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            25 =>
            array (
                'id' => 26,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ISABEL',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            26 =>
            array (
                'id' => 27,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CIENEGUILLA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            27 =>
            array (
                'id' => 28,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PROT. DE CARRETERAS CIENEGUILLA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            28 =>
            array (
                'id' => 29,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA COMAS COLLIQUE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            29 =>
            array (
                'id' => 30,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA LUZMILA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            30 =>
            array (
                'id' => 31,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP TUPAC AMARU',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            31 =>
            array (
                'id' => 32,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA PASCANA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            32 =>
            array (
                'id' => 33,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP COMAS COLLIQUE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            33 =>
            array (
                'id' => 34,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP UNIVERSITARIA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            34 =>
            array (
                'id' => 35,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHACLACAYO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            35 =>
            array (
                'id' => 36,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LADERAS DE VILLA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            36 =>
            array (
                'id' => 37,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHORRILLOS VILLA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            37 =>
            array (
                'id' => 38,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHORRILLOS',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            38 =>
            array (
                'id' => 39,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHORRILLOS MATEO PUMACAHUA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            39 =>
            array (
                'id' => 40,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN GENARO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            40 =>
            array (
                'id' => 41,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP VILLA HERMOSA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            41 =>
            array (
                'id' => 42,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA EL AGUSTINO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            42 =>
            array (
                'id' => 43,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL AGUSTINO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            43 =>
            array (
                'id' => 44,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL AGUSTINO SANTOYO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            44 =>
            array (
                'id' => 45,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN PEDRO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            45 =>
            array (
                'id' => 46,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL AGUSTINO SAN CAYETANO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            46 =>
            array (
                'id' => 47,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN COSME',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            47 =>
            array (
                'id' => 48,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA INDEPENDENCIA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            48 =>
            array (
                'id' => 49,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PAYET',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            49 =>
            array (
                'id' => 50,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP TAHUANTISUYO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            50 =>
            array (
                'id' => 51,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP INDEPENDENCIA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            51 =>
            array (
                'id' => 52,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA UNIFICADA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            52 =>
            array (
                'id' => 53,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP JESÑS MARÑA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            53 =>
            array (
                'id' => 54,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA FELICIA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            54 =>
            array (
                'id' => 55,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA MOLINA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            55 =>
            array (
                'id' => 56,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LAS PRADERAS',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            56 =>
            array (
                'id' => 57,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA VICTORIA APOLO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            57 =>
            array (
                'id' => 58,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA VICTORIA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            58 =>
            array (
                'id' => 59,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PALOMINO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            59 =>
            array (
                'id' => 60,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA BERTHA GONZALES POSADA EYZAGUIRRE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            60 =>
            array (
                'id' => 61,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MIRONES ALTO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            61 =>
            array (
                'id' => 62,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA MIMPV',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            62 =>
            array (
                'id' => 63,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP COTABAMBAS',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            63 =>
            array (
                'id' => 64,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN ANDRES',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            64 =>
            array (
                'id' => 65,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MIRONES BAJO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            65 =>
            array (
                'id' => 66,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PETIT THOUARS',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            66 =>
            array (
                'id' => 67,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP UNIDAD VECINAL NÑ 3',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            67 =>
            array (
                'id' => 68,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CONDE DE LA VEGA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            68 =>
            array (
                'id' => 69,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MONSERRATE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            69 =>
            array (
                'id' => 70,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ESPECIAL DE TURISMO LIMA NORTE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            70 =>
            array (
                'id' => 71,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ALFONSO UGARTE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-02-24 08:16:19',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            71 =>
            array (
                'id' => 72,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LINCE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            72 =>
            array (
                'id' => 73,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SOL DE ORO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            73 =>
            array (
                'id' => 74,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LAURA CALLER IBERICO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            74 =>
            array (
                'id' => 75,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LOS OLIVOS PRO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            75 =>
            array (
                'id' => 76,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LURIGANCHO - HUACHIPA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            76 =>
            array (
                'id' => 77,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHOSICA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            77 =>
            array (
                'id' => 78,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LURIN',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            78 =>
            array (
                'id' => 79,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LURIN VILLA ALEJANDRO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            79 =>
            array (
                'id' => 80,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ESPECIAL DE TURISMO LIMA SUR',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            80 =>
            array (
                'id' => 81,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MAGDALENA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            81 =>
            array (
                'id' => 82,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN ANTONIO DE MIRAFLORES',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            82 =>
            array (
                'id' => 83,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MIRAFLORES',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            83 =>
            array (
                'id' => 84,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MANCHAY',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            84 =>
            array (
                'id' => 85,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PACHACAMAC',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            85 =>
            array (
                'id' => 86,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUCUSANA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            86 =>
            array (
                'id' => 87,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUEBLO LIBRE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            87 =>
            array (
                'id' => 88,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ZAPALLAL',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            88 =>
            array (
                'id' => 89,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUENTE PIEDRA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            89 =>
            array (
                'id' => 90,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA ENSENADA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            90 =>
            array (
                'id' => 91,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUNTA HERMOSA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            91 =>
            array (
                'id' => 92,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUNTA NEGRA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            92 =>
            array (
                'id' => 93,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PIEDRA LIZA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            93 =>
            array (
                'id' => 94,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP RIMAC',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            94 =>
            array (
                'id' => 95,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL MANZANO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            95 =>
            array (
                'id' => 96,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP RIMAC CIUDAD Y CAMPO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            96 =>
            array (
                'id' => 97,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN BARTOLO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            97 =>
            array (
                'id' => 98,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PROT. DE CARRETERAS SAN BARTOLO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            98 =>
            array (
                'id' => 99,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN BORJA CHACARILLA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            99 =>
            array (
                'id' => 100,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN BORJA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            100 =>
            array (
                'id' => 101,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN ISIDRO - ORRANTIA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            101 =>
            array (
                'id' => 102,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN ISIDRO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            102 =>
            array (
                'id' => 103,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA CANTO REY',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            103 =>
            array (
                'id' => 104,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ZARATE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            104 =>
            array (
                'id' => 105,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ELIZABETH',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            105 =>
            array (
                'id' => 106,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP BAYOBAR',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            106 =>
            array (
                'id' => 107,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA HUAYRONA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            107 =>
            array (
                'id' => 108,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP S.J LURIGANCHO MARISCAL CACERES',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            108 =>
            array (
                'id' => 109,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN JUAN DE LURIGANCHO CAJA DE AGUA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            109 =>
            array (
                'id' => 110,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CANTO REY',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            110 =>
            array (
                'id' => 111,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP 10 DE OCTUBRE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-02-24 09:16:30',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            111 =>
            array (
                'id' => 112,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN JUAN DE MIRAFLORES',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            112 =>
            array (
                'id' => 113,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PAMPLONA II',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            113 =>
            array (
                'id' => 114,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA SAN JUAN DE MIRAFLORES',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            114 =>
            array (
                'id' => 115,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PAMPLONA I',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            115 =>
            array (
                'id' => 116,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN LUIS',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            116 =>
            array (
                'id' => 117,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP YERBATEROS',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            117 =>
            array (
                'id' => 118,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP BARBONCITO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            118 =>
            array (
                'id' => 119,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN MARTIN DE PORRES',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            119 =>
            array (
                'id' => 120,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CONDEVILLA SEÑOR',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            120 =>
            array (
                'id' => 121,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN MIGUEL MARANGA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            121 =>
            array (
                'id' => 122,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN MIGUEL',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            122 =>
            array (
                'id' => 123,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ANITA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            123 =>
            array (
                'id' => 124,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA MARIA DEL MAR',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            124 =>
            array (
                'id' => 125,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ROSA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            125 =>
            array (
                'id' => 126,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PROT. DE CARRETERAS SANTA ROSA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            126 =>
            array (
                'id' => 127,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MONTERRICO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            127 =>
            array (
                'id' => 128,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTIAGO DE SURCO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            128 =>
            array (
                'id' => 129,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAGITARIO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            129 =>
            array (
                'id' => 130,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SURQUILLO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            130 =>
            array (
                'id' => 131,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP VILLA EL SALVADOR',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            131 =>
            array (
                'id' => 132,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA VILLA EL SALVADOR',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            132 =>
            array (
                'id' => 133,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP URB. PACHACAMAC',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            133 =>
            array (
                'id' => 134,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP JOSE CARLOS MARIATEGUI',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            134 =>
            array (
                'id' => 135,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN FRANCISCO TABLADA DE LURIN',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            135 =>
            array (
                'id' => 136,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP VILLA MARIA DEL TRIUNFO',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            136 =>
            array (
                'id' => 137,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP NUEVA ESPERANZA',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            137 =>
            array (
                'id' => 138,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP JOSE GALVEZ',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            138 =>
            array (
                'id' => 139,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'MODULO LIMA ESTE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            139 =>
            array (
                'id' => 140,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'MODULO LIMA NORTE',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            140 =>
            array (
                'id' => 141,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'MODULO LIMA SUR',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            141 =>
            array (
                'id' => 142,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'SAU',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            142 =>
            array (
                'id' => 143,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CEM',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => '2019-02-24 09:15:58',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            143 =>
            array (
                'id' => 144,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 1°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:48:03',
                'updated_at' => '2019-02-18 12:00:26',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            144 =>
            array (
                'id' => 145,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 2°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:48:43',
                'updated_at' => '2019-02-18 12:00:40',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            145 =>
            array (
                'id' => 146,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 3°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:49:14',
                'updated_at' => '2019-02-18 12:00:35',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            146 =>
            array (
                'id' => 147,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 4°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:49:43',
                'updated_at' => '2019-02-18 12:01:00',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            147 =>
            array (
                'id' => 148,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'nombre' => 'COMISARIA DE PACHACUTEC',
                'sigla' => 'CP',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-17 10:54:07',
                'updated_at' => '2019-02-17 10:54:07',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            148 =>
            array (
                'id' => 149,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'nombre' => 'COMISARIA DE VENTANILLA',
                'sigla' => 'CV',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-17 10:54:31',
                'updated_at' => '2019-02-17 10:54:31',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            149 =>
            array (
                'id' => 150,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'nombre' => 'COMISARIA VILLA LOS REYES',
                'sigla' => 'CVR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-17 11:41:24',
                'updated_at' => '2019-02-17 11:41:24',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            150 =>
            array (
                'id' => 151,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'nombre' => 'COMISARIA DE SANTA ROSA',
                'sigla' => 'CSR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-03-13 15:22:08',
                'updated_at' => '2019-03-13 15:22:08',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            151 =>
            array (
                'id' => 152,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'nombre' => 'COMISARIA DE ANCON',
                'sigla' => 'CA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-03-13 15:22:21',
                'updated_at' => '2019-03-13 15:22:21',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
            152 =>
            array (
                'id' => 153,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'nombre' => 'COMISARIA DE MI PERU',
                'sigla' => 'CMP',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-03-29 10:37:05',
                'updated_at' => '2019-03-29 10:37:05',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),

            153 =>
            array (
                'id' => 154,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 5°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:50:12',
                'updated_at' => '2019-02-18 12:00:49',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            154 =>
            array (
                'id' => 155,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 6°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:56:53',
                'updated_at' => '2019-02-18 12:00:54',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            155 =>
            array (
                'id' => 156,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 7°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-21 14:36:20',
                'updated_at' => '2019-03-08 13:27:47',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            156 =>
            array (
                'id' => 157,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 8°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-21 14:38:06',
                'updated_at' => '2019-02-25 09:13:00',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            157 =>
            array (
                'id' => 158,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 9°',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-03-08 13:22:38',
                'updated_at' => '2019-03-08 13:27:17',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            158 =>
            array (
                'id' => 159,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Alto de la Alianza',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-03-08 13:24:40',
                'updated_at' => '2019-03-08 13:29:39',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            159 =>
            array (
                'id' => 160,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de AGregorio Albarracín',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-03-08 13:34:20',
                'updated_at' => '2019-03-08 13:35:43',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            160 =>
            array (
                'id' => 161,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Tarata',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:49:43',
                'updated_at' => '2019-02-18 12:01:00',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            161 =>
            array (
                'id' => 162,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Candarave',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:50:12',
                'updated_at' => '2019-02-18 12:00:49',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            162 =>
            array (
                'id' => 163,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Jorge Basadre',
                'sigla' => NULL,
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => '2019-02-18 11:56:53',
                'updated_at' => '2019-02-18 12:00:54',
                'deleted_at' => NULL,
                'tipo_int' => 1,
                'color' => 'light_blue',
            ),
            163 =>
            array (
                'id' => 164,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'CENTRO EMERGENCIA MUJER TACNA',
                'sigla' => 'CEM-TACNA',
                'latitud' => '-18.011341582086402',
                'longitud' => '-70.25054355844418',
                'created_at' => '2019-02-21 14:36:20',
                'updated_at' => '2019-03-08 13:27:47',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'red',
            ),
            164 =>
            array (
                'id' => 165,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Minestrio Público Tacna',
                'sigla' => 'MP',
                'latitud' => '-18.0108211',
                'longitud' => '-70.2540033',
                'created_at' => '2019-02-21 14:38:06',
                'updated_at' => '2019-02-25 09:13:00',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'blue',
            ),
            165 =>
            array (
                'id' => 166,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'CENTRO EMERGENCIA MUJER GAL',
                'sigla' => 'CEM-GAL',
                'latitud' => '-18.041986503754533',
                'longitud' => '-70.25125025169348',
                'created_at' => '2019-03-08 13:22:38',
                'updated_at' => '2019-03-08 13:27:17',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'red',
            ),
            166 =>
            array (
                'id' => 167,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'CENTRO EMERGENCIA MUJER CIUDAD NUEVA',
                'sigla' => 'CEM-CN',
                'latitud' => '-17.984370341976753',
                'longitud' => '-70.23550628987459',
                'created_at' => '2019-03-08 13:24:40',
                'updated_at' => '2019-03-08 13:29:39',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'red',
            ),
            167 =>
            array (
                'id' => 168,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'MODULO ALTO DE LA ALIANZA',
                'sigla' => 'MDO-AA',
                'latitud' => '-17.98810082861647',
                'longitud' => '-70.24017069769707',
                'created_at' => '2019-03-08 13:34:20',
                'updated_at' => '2019-03-08 13:35:43',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'yellow',
            ),
            168 =>
            array (
                'id' => 169,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'COMISARIA DE FAMILIA TACNA',
                'sigla' => 'CF',
                'latitud' => '-18.007169654457357',
                'longitud' => '-70.25565125192117',
                'created_at' => '2019-03-18 13:06:35',
                'updated_at' => '2019-03-18 15:05:51',
                'deleted_at' => NULL,
                'tipo_int' => 0,
                'color' => 'green',
            ),
        ));


    }
}
