<?php

use Illuminate\Database\Seeder;

class TblcomisariaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tblcomisaria')->delete();
        
        \DB::table('tblcomisaria')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Familia',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Otros',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Gregorio Albarracín',
                'latitud' => '-18.041866',
                'longitud' => '-70.251253',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Ciudad Nueva',
                'latitud' => '-17.984271',
                'longitud' => '-70.235475',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Alto de la Alianza',
                'latitud' => '-17.987922',
                'longitud' => '-70.241195',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Central',
                'latitud' => '-18.014765',
                'longitud' => '-70.251784',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Natividad',
                'latitud' => '-18.011738',
                'longitud' => '-70.233184',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Leguía',
                'latitud' => '-18.034372',
                'longitud' => '-70.276660',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Pocollay',
                'latitud' => '-17.995188',
                'longitud' => '-70.220063',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Vigil',
                'latitud' => '-17.997524',
                'longitud' => '-70.245652',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Pachia',
                'latitud' => '-17.895296',
                'longitud' => '-70.152744',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Boca del Rio',
                'latitud' => '-18.156744',
                'longitud' => '-70.679107',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Calana',
                'latitud' => '-17.940560',
                'longitud' => '-70.186899',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Sama las Yaras',
                'latitud' => '-17.862860',
                'longitud' => '-70.560096',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Sama Inclan',
                'latitud' => '-17.794749',
                'longitud' => '-70.494779',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'nombre' => 'Ite',
                'latitud' => '-17.861950',
                'longitud' => '-70.965062',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ANCON',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP VITARTE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ROSA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP HUAYCAN',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SALAMANCA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP BARRANCO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP BREÑA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CARABAYLLO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL PROGRESO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ISABEL',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CIENEGUILLA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PROT. DE CARRETERAS CIENEGUILLA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA COMAS COLLIQUE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA LUZMILA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP TUPAC AMARU',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA PASCANA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP COMAS COLLIQUE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP UNIVERSITARIA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHACLACAYO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LADERAS DE VILLA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHORRILLOS VILLA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHORRILLOS',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHORRILLOS MATEO PUMACAHUA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN GENARO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP VILLA HERMOSA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA EL AGUSTINO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL AGUSTINO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL AGUSTINO SANTOYO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN PEDRO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL AGUSTINO SAN CAYETANO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN COSME',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA INDEPENDENCIA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PAYET',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP TAHUANTISUYO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP INDEPENDENCIA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA UNIFICADA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP JESÑS MARÑA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA FELICIA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA MOLINA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LAS PRADERAS',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA VICTORIA APOLO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA VICTORIA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PALOMINO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA BERTHA GONZALES POSADA EYZAGUIRRE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MIRONES ALTO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA MIMPV',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP COTABAMBAS',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN ANDRES',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MIRONES BAJO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PETIT THOUARS',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP UNIDAD VECINAL NÑ 3',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CONDE DE LA VEGA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MONSERRATE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ESPECIAL DE TURISMO LIMA NORTE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ALFONSO UGARTE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LINCE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SOL DE ORO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LAURA CALLER IBERICO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LOS OLIVOS PRO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LURIGANCHO - HUACHIPA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CHOSICA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LURIN',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LURIN VILLA ALEJANDRO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ESPECIAL DE TURISMO LIMA SUR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MAGDALENA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN ANTONIO DE MIRAFLORES',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MIRAFLORES',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MANCHAY',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PACHACAMAC',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUCUSANA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUEBLO LIBRE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ZAPALLAL',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUENTE PIEDRA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA ENSENADA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUNTA HERMOSA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PUNTA NEGRA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PIEDRA LIZA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP RIMAC',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP EL MANZANO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP RIMAC CIUDAD Y CAMPO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN BARTOLO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PROT. DE CARRETERAS SAN BARTOLO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN BORJA CHACARILLA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN BORJA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN ISIDRO - ORRANTIA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN ISIDRO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA CANTO REY',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP ZARATE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ELIZABETH',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP BAYOBAR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP LA HUAYRONA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP S.J LURIGANCHO MARISCAL CACERES',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN JUAN DE LURIGANCHO CAJA DE AGUA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CANTO REY',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            110 => 
            array (
                'id' => 111,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP 10 DE OCTUBRE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            111 => 
            array (
                'id' => 112,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN JUAN DE MIRAFLORES',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            112 => 
            array (
                'id' => 113,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PAMPLONA II',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            113 => 
            array (
                'id' => 114,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA SAN JUAN DE MIRAFLORES',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            114 => 
            array (
                'id' => 115,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PAMPLONA I',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            115 => 
            array (
                'id' => 116,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN LUIS',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            116 => 
            array (
                'id' => 117,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP YERBATEROS',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            117 => 
            array (
                'id' => 118,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP BARBONCITO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            118 => 
            array (
                'id' => 119,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN MARTIN DE PORRES',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            119 => 
            array (
                'id' => 120,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP CONDEVILLA SEÑOR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            120 => 
            array (
                'id' => 121,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN MIGUEL MARANGA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            121 => 
            array (
                'id' => 122,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN MIGUEL',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            122 => 
            array (
                'id' => 123,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ANITA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            123 => 
            array (
                'id' => 124,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA MARIA DEL MAR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            124 => 
            array (
                'id' => 125,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTA ROSA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            125 => 
            array (
                'id' => 126,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP PROT. DE CARRETERAS SANTA ROSA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            126 => 
            array (
                'id' => 127,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP MONTERRICO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            127 => 
            array (
                'id' => 128,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SANTIAGO DE SURCO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            128 => 
            array (
                'id' => 129,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAGITARIO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            129 => 
            array (
                'id' => 130,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SURQUILLO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            130 => 
            array (
                'id' => 131,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP VILLA EL SALVADOR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            131 => 
            array (
                'id' => 132,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP DE LA FAMILIA VILLA EL SALVADOR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            132 => 
            array (
                'id' => 133,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP URB. PACHACAMAC',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            133 => 
            array (
                'id' => 134,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP JOSE CARLOS MARIATEGUI',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            134 => 
            array (
                'id' => 135,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP SAN FRANCISCO TABLADA DE LURIN',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            135 => 
            array (
                'id' => 136,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP VILLA MARIA DEL TRIUNFO',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            136 => 
            array (
                'id' => 137,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP NUEVA ESPERANZA',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            137 => 
            array (
                'id' => 138,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CPNP JOSE GALVEZ',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            138 => 
            array (
                'id' => 139,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'MODULO LIMA ESTE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            139 => 
            array (
                'id' => 140,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'MODULO LIMA NORTE',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            140 => 
            array (
                'id' => 141,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'MODULO LIMA SUR',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            141 => 
            array (
                'id' => 142,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'SAU',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            142 => 
            array (
                'id' => 143,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'nombre' => 'CEM',
                'latitud' => NULL,
                'longitud' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}