<?php

use Illuminate\Database\Seeder;

class TblinstanciaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tblinstancia')->delete();
        
        \DB::table('tblinstancia')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1° Juzgado Civil',
                'sigla' => '1JCI',
                'tipo' => 'CI',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2° Juzgado Civil',
                'sigla' => '2JCI',
                'tipo' => 'CI',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '3° Juzgado Civil',
                'sigla' => '3JC',
                'tipo' => 'CI',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1° Juzgado de Paz Letrado',
                'sigla' => '2JPL',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2° Juzgado de Paz Letrado',
                'sigla' => '3JPL',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'EXHORTO',
                'sigla' => 'EXH',
                'tipo' => NULL,
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Mixto - MBJ Alto del Alianza',
                'sigla' => 'JM-AA',
                'tipo' => 'JM',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juz. Inv. Prep - MBJ AA',
                'sigla' => '1JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juz. Inv. Preparatoria - Sede Tarata',
                'sigla' => 'JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2° Juz. Inv. Prep. - FLAGRANCIA, OAF Y CEED',
                'sigla' => '2JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Sala Penal de Apelaciones',
                'sigla' => '1SAP',
                'tipo' => 'SP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '5° Juzgado de Investigación Preparatoria - Flagrancia',
                'sigla' => '5JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1° Sala Civil',
                'sigla' => 'SC',
                'tipo' => 'SC',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1° Juzgado Unipersonal Supraprovincial',
                'sigla' => '1JUN',
                'tipo' => 'PU',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Paz Letrado Laboral',
                'sigla' => '1JPL',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Trabajo Transitorio',
                'sigla' => '1JTT',
                'tipo' => 'LA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Penal Colegiado Supraprovincial',
                'sigla' => '1JPC',
                'tipo' => 'JP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '3° Juzgado de Paz Letrado',
                'sigla' => '3JPL',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Sala Laboral Permanente',
                'sigla' => 'SL',
                'tipo' => 'SL',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2° Juzgado Unipersonal Supraprovincial - FLAGRANCIA, OAF Y CEED',
                'sigla' => '2JUN',
                'tipo' => 'PU',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1° Juzgado de Trabajo',
                'sigla' => '1JT',
                'tipo' => 'LA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2° Juzgado Especializado de Trabajo',
                'sigla' => '2JTR',
                'tipo' => 'LA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '4° Juzgado de Investigación Preparatoria',
                'sigla' => '4JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Civil Transitorio',
                'sigla' => '1JCT',
                'tipo' => 'CI',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1° Juzgado de Familia',
                'sigla' => '1JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2° Juzgado de Familia',
                'sigla' => '2JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Mixto - Sede Locumba',
                'sigla' => 'JM-JB',
                'tipo' => 'JM',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juz. de Familia Tran. - MBJ GAL',
                'sigla' => 'JFT-GAL',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '6° Juzgado Inv. Preparatoria - DELITO AD. TRIB. MCDO. Y AMB',
                'sigla' => '6JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '3° Juzgado de Trabajo',
                'sigla' => '3JT',
                'tipo' => 'LA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '4° Juzgado Civil',
                'sigla' => '4JC',
                'tipo' => 'CI',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2° Sala Civil',
                'sigla' => '2SC',
                'tipo' => 'SC',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Mixto - Tarata',
                'sigla' => 'JM-TA',
                'tipo' => 'JM',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '3° Juzgado Unipersonal Supraprovincial',
                'sigla' => '3JUN',
                'tipo' => 'PU',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '3° Juzgado de Investigación Preparatoria',
                'sigla' => '3JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1° Juzgado de Investigación Preparatoria',
                'sigla' => '1JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '3° Juzgado de Familia',
                'sigla' => '3JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '4° Juzgado de Familia',
                'sigla' => '4JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
            'nombre' => 'Juz. Penal Liquidador (Ad. Funciones 5° JIP)- Sede Central',
                'sigla' => '5JP',
                'tipo' => 'JP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Unipersonal - Sede Tarata',
                'sigla' => 'JU',
                'tipo' => NULL,
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juz. de Paz Letrado - MBJ Alto del Alianza',
                'sigla' => 'JPL',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juz. de Paz Letrado - Sede Tarata',
                'sigla' => 'JPL',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juz. Inv. Prep. - MBJ GAL',
                'sigla' => '1JIP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
            'nombre' => 'Sala Penal Liquidadora(Ad. Func. Sala Penal Apelac.)',
                'sigla' => '1SPL',
                'tipo' => 'SP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
            'nombre' => 'Juzgado Penal Liquidador (AD Funciones 4° JIP)',
                'sigla' => '1JPL',
                'tipo' => 'JP',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'OTROS',
                'sigla' => 'OTR',
                'tipo' => NULL,
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Mixto - Candarave',
                'sigla' => 'JM-CA',
                'tipo' => 'JM',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '9° Juzgado de Familia',
                'sigla' => '9JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '10° Juzgado de Familia',
                'sigla' => '10JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '11° Juzgado de Familia',
                'sigla' => '11JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '12° Juzgado de Familia',
                'sigla' => '12JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '13° Juzgado de Familia',
                'sigla' => '13JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '14° Juzgado de Familia',
                'sigla' => '14JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '15° Juzgado de Familia',
                'sigla' => '15JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '16° Juzgado de Familia',
                'sigla' => '16JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'tblmodulo_id' => NULL,
                'tbldepartamento_id' => 15,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '17° Juzgado de Familia',
                'sigla' => '17JF',
                'tipo' => 'FA',
                'estadistica' => 0,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1° JUZGADO DE FAMILIA - SEDE ANEXO 1',
                'sigla' => '1JFSA1',
                'tipo' => 'FA',
                'estadistica' => 1,
                'created_at' => '2019-02-14 23:21:48',
                'updated_at' => '2019-02-14 23:21:48',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2° JUZGADO DE FAMILIA - SEDE JUZG. FAMILIA',
                'sigla' => '2JFSJF',
                'tipo' => 'FA',
                'estadistica' => 1,
                'created_at' => '2019-02-14 23:22:21',
                'updated_at' => '2019-02-14 23:22:21',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'JUZGADO CIVIL - SEDE ANCON',
                'sigla' => 'JCSA',
                'tipo' => 'CI',
                'estadistica' => 1,
                'created_at' => '2019-02-14 23:22:49',
                'updated_at' => '2019-02-14 23:22:49',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'JUZGADO CIVIL - SEDE MI PERÚ',
                'sigla' => 'JCSMP',
                'tipo' => 'CI',
                'estadistica' => 1,
                'created_at' => '2019-02-14 23:23:15',
                'updated_at' => '2019-02-14 23:23:15',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'JUZGADO CIVIL - SEDE PACHACÚTEC',
                'sigla' => 'JCSP',
                'tipo' => 'CI',
                'estadistica' => 1,
                'created_at' => '2019-02-14 23:23:42',
                'updated_at' => '2019-02-14 23:23:42',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'JUZGADO CIVIL TRANSITORIO - SEDE ANCON',
                'sigla' => 'JCTSA',
                'tipo' => 'CI',
                'estadistica' => 1,
                'created_at' => '2019-02-14 23:23:42',
                'updated_at' => '2019-06-20 20:17:31',
                'deleted_at' => '2019-06-20 20:17:31',
            ),
            62 => 
            array (
                'id' => 63,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 1°',
                'sigla' => 'FPC-T1',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:26:06',
                'updated_at' => '2019-02-18 15:33:15',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 2°',
                'sigla' => 'FPC-T2',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:26:07',
                'updated_at' => '2019-02-18 15:33:07',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 3°',
                'sigla' => 'FPC-T3',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:30:54',
                'updated_at' => '2019-02-18 16:02:42',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 4°',
                'sigla' => 'FPC-T4',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:31:23',
                'updated_at' => '2019-02-18 16:02:57',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 5°',
                'sigla' => 'FPC-T5',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:31:44',
                'updated_at' => '2019-02-18 16:02:22',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 6°',
                'sigla' => 'FPC-T6',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:32:21',
                'updated_at' => '2019-02-18 16:02:48',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 7°',
                'sigla' => 'FPC-T7',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:26:06',
                'updated_at' => '2019-02-18 15:33:15',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 8°',
                'sigla' => 'FPC-T8',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:26:06',
                'updated_at' => '2019-02-18 15:33:15',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Corporativa de Tacna 9°',
                'sigla' => 'FPC-T9',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:26:06',
                'updated_at' => '2019-02-18 15:33:15',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Alto de la Alianza',
                'sigla' => 'FP-AL',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:26:07',
                'updated_at' => '2019-02-18 15:33:07',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Gregorio Albarracín',
                'sigla' => 'FP-GAL',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:30:54',
                'updated_at' => '2019-02-18 16:02:42',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Tarata',
                'sigla' => 'FP-T',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:31:23',
                'updated_at' => '2019-02-18 16:02:57',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Candarave',
                'sigla' => 'FP-C',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:31:44',
                'updated_at' => '2019-02-18 16:02:22',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Mixta Corporativa de Jorge Basadre',
                'sigla' => 'FP-JB',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-02-18 15:32:21',
                'updated_at' => '2019-02-18 16:02:48',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1º Fiscalía Provincial Penal Corporativa de Ventanilla',
                'sigla' => '1FPPCV',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:06:31',
                'updated_at' => '2019-05-23 01:06:31',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2º Fiscalía Provincial Penal Corporativa de Ventanilla',
                'sigla' => '2FPPCV',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:07:07',
                'updated_at' => '2019-05-23 01:07:07',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '3º Fiscalía Provincial Penal Corporativa de Ventanilla',
                'sigla' => '3FPPCV',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:07:30',
                'updated_at' => '2019-05-23 01:07:30',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '4º Fiscalía Provincial Penal Corporativa de Ventanilla',
                'sigla' => '4FPPCV',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:07:48',
                'updated_at' => '2019-05-23 01:07:48',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '5º Fiscalía Provincial Penal Corporativa de Ventanilla',
                'sigla' => '5FPPCV',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:08:05',
                'updated_at' => '2019-05-23 01:08:05',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Fiscalía Provincial Penal Corporativa de Mi Perú',
                'sigla' => 'FPPCMP',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:08:29',
                'updated_at' => '2019-05-23 01:08:29',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1º Fiscalía Provincial Penal Corporativa de Santa Rosa - Ancón',
                'sigla' => '1FPPCSRA',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:09:15',
                'updated_at' => '2019-05-23 01:09:15',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2º Fiscalía Provincial Penal Corporativa de Santa Rosa - Ancón',
                'sigla' => '2FPPCSRA',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:09:33',
                'updated_at' => '2019-05-23 01:09:33',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '3º Fiscalía Provincial Penal Corporativa de Santa Rosa - Ancón',
                'sigla' => '3FPPCSRA',
                'tipo' => 'MP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:09:49',
                'updated_at' => '2019-05-23 01:09:49',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1º Juzgado de Paz Letrado Ventanilla',
                'sigla' => '1JPLV',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:12:35',
                'updated_at' => '2019-05-23 01:12:35',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2º Juzgado de Paz Letrado Ventanilla',
                'sigla' => '2JPLV',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:15:45',
                'updated_at' => '2019-05-23 01:15:45',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Paz Letrado de Trabajo Ventanilla',
                'sigla' => 'JPLTV',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:16:32',
                'updated_at' => '2019-05-23 01:16:32',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Paz Letrado Mi Peru',
                'sigla' => 'JPLMP',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:17:03',
                'updated_at' => '2019-05-23 01:17:03',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Paz Letrado Ancon y Santa Rosa',
                'sigla' => 'JPLASR',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:17:45',
                'updated_at' => '2019-05-23 01:17:45',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Paz Letrado Pachacutec',
                'sigla' => 'JPLP',
                'tipo' => 'PL',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:18:20',
                'updated_at' => '2019-05-23 01:18:20',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Investigación Preparatoria Mi Peru',
                'sigla' => 'JIPMP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:20:59',
                'updated_at' => '2019-05-23 01:20:59',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Investigación Preparatoria Transitoria Mi Peru',
                'sigla' => 'JIPTMP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:21:23',
                'updated_at' => '2019-05-23 01:21:23',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Investigación Preparatoria Ancon y Santa Rosa',
                'sigla' => 'JIPASR',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:21:53',
                'updated_at' => '2019-05-23 01:21:53',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado de Investigación Preparatoria Pachacutec',
                'sigla' => 'JIPP',
                'tipo' => 'IP',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:22:16',
                'updated_at' => '2019-05-23 01:22:16',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Penal Unipersonal Mi Peru',
                'sigla' => 'JPUMP',
                'tipo' => 'PU',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:23:09',
                'updated_at' => '2019-05-23 01:23:09',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => 'Juzgado Penal Unipersonal Ancon y Santa Rosa',
                'sigla' => 'JPUASR',
                'tipo' => 'PU',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:23:45',
                'updated_at' => '2019-05-23 01:23:45',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '1º Juzgado Penal Unipersonal Transitorio Pachacutec',
                'sigla' => '1JPUTP',
                'tipo' => 'PU',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:24:55',
                'updated_at' => '2019-05-23 01:24:55',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'tblprovincia_id' => NULL,
                'tbldistrito_id' => NULL,
                'nombre' => '2º Juzgado Penal Unipersonal Transitorio Pachacutec',
                'sigla' => '2JPUTP',
                'tipo' => 'PU',
                'estadistica' => 0,
                'created_at' => '2019-05-23 01:25:16',
                'updated_at' => '2019-05-23 01:25:16',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}