<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'name' => 'admin',
                'email' => 'admin@admin.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$TKh8H1.PfQx37YgCzwiKb.KjNyWgaHb9cbcoQgdIVFlYg7B77UdFm',
                'nombre' => 'Administrador General',
                'dni' => '47839757',
                'fchnac' => '1993-07-17',
                'direccion' => 'Dstr. Gregorio Albarracin Las Americas Ñ 11',
                'fono' => '47839757',
                'imagen' => NULL,
                'lat' => '-18.0092832',
                'lng' => '-70.2438729',
                'acceso' => 1,
                'remember_token' => 'L8l2YfS3O8UwPpWkdDuUPXTf1nUHzzO4Z6ZPNSQ7019dQafXLvP6DKnrV2FZ',
                'created_at' => '2019-04-23 07:57:07',
                'updated_at' => '2019-09-25 16:58:50',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'name' => 'adminmod',
                'email' => 'adminmod@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$TKh8H1.PfQx37YgCzwiKb.KjNyWgaHb9cbcoQgdIVFlYg7B77UdFm',
                'nombre' => 'Administrador General MT',
                'dni' => '32659865',
                'fchnac' => '1990-01-01',
                'direccion' => 'Tacna',
                'fono' => '052580003',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 1,
                'remember_token' => 'TXGWpXPpUc',
                'created_at' => '2019-04-23 07:57:07',
                'updated_at' => '2019-04-23 07:57:07',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'name' => 'pnptacna',
                'email' => 'pnptacna@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$TKh8H1.PfQx37YgCzwiKb.KjNyWgaHb9cbcoQgdIVFlYg7B77UdFm',
                'nombre' => 'PNP Tacna',
                'dni' => '32216554',
                'fchnac' => '1990-01-01',
                'direccion' => 'Direccion',
                'fono' => '965542132',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 1,
                'remember_token' => 'lvapwSxWYG',
                'created_at' => '2019-04-23 07:57:07',
                'updated_at' => '2019-04-23 07:57:07',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'name' => 'asistenteventanilla',
                'email' => 'asistenteventanilla@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$O5WmJe0gmgZ7ozNAdvZPGOg.W66F.mOAJgEB0VBovzS61oq4xdw96',
                'nombre' => 'Asistente Ventanilla',
                'dni' => '32659887',
                'fchnac' => '1990-06-12',
                'direccion' => 'Ventanilla',
                'fono' => '58986598',
                'imagen' => NULL,
                'lat' => '-11.877127759242562',
                'lng' => '-77.12577223777771',
                'acceso' => 1,
                'remember_token' => 'qFxrVGHNzF8fisHLeeVWUrDUfDL8bsuHMiOlYt6oZYa4cwCBNNhxbQGnjNIc',
                'created_at' => '2019-04-23 08:12:27',
                'updated_at' => '2019-06-25 11:50:57',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'name' => 'adminventanilla',
                'email' => 'adminventanilla@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$8TATiAFnas33hhqnh2MI7ePgN5KL4Yx0/wdAG1UgLSb6r1KJkzGb6',
                'nombre' => 'Administrador Ventanilla',
                'dni' => '31649584',
                'fchnac' => '1990-06-12',
                'direccion' => 'Ventanilla',
                'fono' => '965986532',
                'imagen' => NULL,
                'lat' => '-11.877131696421838',
                'lng' => '-77.12578095495701',
                'acceso' => 1,
                'remember_token' => 'SEksycjYE2jzftsTfY66u94l1H7zdWc8xzQwJ2rXqYNhW5bdzjY9NMHyW6Cw',
                'created_at' => '2019-04-23 08:24:36',
                'updated_at' => '2019-09-28 11:38:01',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'name' => 'pnpventanilla',
                'email' => 'pnpventanilla@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$w858EpqdrJrZC6KlGTmcAekGqJ5m7xhP5ioRpW5q2fXqVDR4nCVUO',
                'nombre' => 'PNP Ventanilla',
                'dni' => '61946194',
                'fchnac' => '1990-06-19',
                'direccion' => 'Ventanilla',
                'fono' => '954848754',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 1,
                'remember_token' => 'mAlZAtBR5vfC7hffqLgVyBMXEhEmOhxnJYkH5wgbhQ3MpsNpydGe34wKlVKt',
                'created_at' => '2019-04-23 08:26:16',
                'updated_at' => '2019-04-23 08:26:16',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'tblmodulo_id' => 18,
                'tbldepartamento_id' => 15,
                'name' => 'milagrosc',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$wrhDqUqqxX0dQizvBlzb0uEUwBGo4RTpP.u56GsO0pVa/KVo4r.aq',
                'nombre' => 'MILAGROS DEL CARMEN',
                'dni' => '78182931',
                'fchnac' => NULL,
                'direccion' => 'Jr. Godofredo Garcia 542 - Urb. Micaela Bastidas - Los Olivos 2do piso',
                'fono' => '987654321',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-02 12:52:57',
                'updated_at' => '2019-09-02 12:57:19',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'tblmodulo_id' => 18,
                'tbldepartamento_id' => 15,
                'name' => 'Tatiana',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$DSNQW/Zw9jbNPNPMp9yRBuer0sYsFralFiAMoWVbW4V1dce0q2z8e',
                'nombre' => 'TATIANA LISETH',
                'dni' => '77393468',
                'fchnac' => NULL,
                'direccion' => 'Lima',
                'fono' => '987654321',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-02 14:28:27',
                'updated_at' => '2019-09-02 14:30:13',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'tblmodulo_id' => 7,
                'tbldepartamento_id' => 7,
                'name' => 'Rolandoed',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$LHvAZXK3FBL0fHL4O6JH8.CB/RUKnv.j9iW98SKLpYce8A9297N/i',
                'nombre' => 'ROLANDO EDWIN',
                'dni' => '25579902',
                'fchnac' => NULL,
                'direccion' => 'Lima',
                'fono' => '987654321',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-02 14:42:09',
                'updated_at' => '2019-09-02 14:42:39',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'tblmodulo_id' => 33,
                'tbldepartamento_id' => 7,
                'name' => 'uconsultaventanilla',
                'email' => 'uconsultaventanilla@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$a/UzZ9nno5kS/dX.dzdtmuM4pLUTE/8nJaSS4fR4qrgI1BwSWZi/e',
                'nombre' => 'Usuario Consulta',
                'dni' => '12345678',
                'fchnac' => '1990-06-12',
                'direccion' => 'Urb. Pedro Cueva Mz. B 4',
                'fono' => '987654321',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 1,
                'remember_token' => NULL,
                'created_at' => '2019-09-05 10:49:11',
                'updated_at' => '2019-09-05 10:49:11',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'tblmodulo_id' => 7,
                'tbldepartamento_id' => 7,
                'name' => 'aurora',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$XxAzkPoMB.ScC15uFHuBwODJjk2d8IYxSjWKLINvFZqYq4xJYd2f6',
                'nombre' => 'AURORA',
                'dni' => '41614328',
                'fchnac' => NULL,
                'direccion' => NULL,
                'fono' => NULL,
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-25 16:55:05',
                'updated_at' => '2019-09-25 16:55:05',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'tblmodulo_id' => 30,
                'tbldepartamento_id' => 23,
                'name' => 'kimberly',
                'email' => 'kimberly@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$OTgcJFlfpq0KItbLiJOte.67wHKABie7AXKPJzmDEpO.zM3xwBj1W',
                'nombre' => 'Kimberly Guzman',
                'dni' => '70865290',
                'fchnac' => '1990-09-03',
                'direccion' => 'Modulo de Familia de Tacna',
                'fono' => '986525252',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 1,
                'remember_token' => 'ye5pg09LtHsNfZdC7a6Pl3Ak9CU8kks2NzS4m5CSfd5PAwupd1ktRaBcXQjx',
                'created_at' => '2019-09-25 17:01:23',
                'updated_at' => '2019-09-25 17:01:23',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'tblmodulo_id' => 7,
                'tbldepartamento_id' => 7,
                'name' => 'estefany',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$fYnV9IKPcFv.y3TF3SLg/OWzhdAFeN0vVronftRc/7rIy2M2HWVPG',
                'nombre' => 'Estefany del Rosario',
                'dni' => '76116886',
                'fchnac' => NULL,
                'direccion' => 'Dirección',
                'fono' => '987987987',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-27 11:54:09',
                'updated_at' => '2019-09-27 11:54:33',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'tblmodulo_id' => 7,
                'tbldepartamento_id' => 7,
                'name' => 'nieves',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$4jBewW552h.PPACrnUw/7.qXGlNXpx8VFXZ9/yxnoTJbTd9vrZ8uK',
                'nombre' => 'NIEVES NATHALY',
                'dni' => '76877550',
                'fchnac' => NULL,
                'direccion' => 'Dirección',
                'fono' => '954765476',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-27 13:13:17',
                'updated_at' => '2019-09-27 13:13:44',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'tblmodulo_id' => 7,
                'tbldepartamento_id' => 7,
                'name' => 'sabina',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$cQ00PVkgY1v50JzhnlNdjOyEkecAizpXHWJ30N1pc7ngl4qZWLmaK',
                'nombre' => 'SABINA CONCEPCION',
                'dni' => '10438874',
                'fchnac' => NULL,
                'direccion' => 'Dirección',
                'fono' => '945324567',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-27 13:41:08',
                'updated_at' => '2019-09-27 13:41:25',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'tblmodulo_id' => 18,
                'tbldepartamento_id' => 15,
                'name' => 'andrea',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$BUFQf/drRl44CjEDjQ/cm.yD3x4GAO8L6upNzlFrmo6CfAdog61sm',
                'nombre' => 'ANDREA DEL PILAR',
                'dni' => '47178150',
                'fchnac' => NULL,
                'direccion' => NULL,
                'fono' => NULL,
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-27 17:01:38',
                'updated_at' => '2019-09-27 17:01:38',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'tblmodulo_id' => 18,
                'tbldepartamento_id' => 15,
                'name' => 'rosimary',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$7l4ooDw1LVErvj6iMkpGIONia6ZWAW7KwWqOdr/qeh8eGT.HiP4si',
                'nombre' => 'ROSI MARY',
                'dni' => '45510328',
                'fchnac' => NULL,
                'direccion' => 'Dirección',
                'fono' => '954635422',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-27 17:40:57',
                'updated_at' => '2019-09-27 17:42:09',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'tblmodulo_id' => 7,
                'tbldepartamento_id' => 7,
                'name' => 'jorgeal',
                'email' => NULL,
                'email_verified_at' => NULL,
                'password' => '$2y$10$vN1/KKwpiaRgQDOS/hvEVuqLBCDNhxYoMtxd6pmZH6jbXsX95Uxqy',
                'nombre' => 'JORGE ALFREDO',
                'dni' => '80417468',
                'fchnac' => NULL,
                'direccion' => 'Dirección',
                'fono' => '998877665',
                'imagen' => NULL,
                'lat' => NULL,
                'lng' => NULL,
                'acceso' => 0,
                'remember_token' => NULL,
                'created_at' => '2019-09-27 17:49:17',
                'updated_at' => '2019-09-30 01:10:12',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}